name: Deploy Dev

on:
  push:
    branches: [ "development" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
     uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with: 
        username: ${{secrets.DOCKER_USER_NAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and Push the Docker image
      uses: docker/build-push-action@v3.1.1
      with:   
        push: true
        tags: deploy-test/server:dev-latest


      # run: docker build . --file Dockerfile --tag workflow-server-dev:$(date +%s)
